[package]
name = "crawler"
version = "0.1.0"
authors = ["sparrrgh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "0.9.0"
#url = "2.1.1"
failure = "0.1.5"
chrono = "0.4.19"